export const CONFIG_SAVED = 'CONFIG_SAVED';
export const CONFIG_SAVE_FAILED = 'CONFIG_SAVE_FAILED';
export const DISMISS_ALERTS = 'DISMISS_ALERTS';
export const INIT_CONFIG_SAVE = 'INIT_CONFIG_SAVE';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
export const TOGGLE_ISENABLED = 'TOGGLE_ISENABLED';
